brew 'vim'
brew 'neovim'
brew 'peco'
brew 'htop'
brew 'lv'

cask 'karabiner-elements'
cask 'iterm2'
cask 'google-chrome'
cask 'clipy'
cask 'rectangle'
cask 'visual-studio-code'
cask 'flux'
cask 'git-credential-manager'
cask 'google-japanese-ime'
