name: Dotfiles CI for macOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-dotfiles:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: run setup
        run: bash ./setup.sh
